FROM rabbitmq:3.7
COPY accept-0.3.3.ez /opt/rabbitmq/plugins/accept-0.3.3.ez
COPY prometheus-3.5.1.ez /opt/rabbitmq/plugins/prometheus-3.5.1.ez
COPY prometheus_cowboy-0.1.4.ez /opt/rabbitmq/plugins/prometheus_cowboy-0.1.4.ez
COPY prometheus_httpd-2.1.8.ez /opt/rabbitmq/plugins/prometheus_httpd-2.1.8.ez
COPY prometheus_process_collector-1.3.1.ez /opt/rabbitmq/plugins/prometheus_process_collector-1.3.1.ez
COPY prometheus_rabbitmq_exporter-3.7.2.3.ez /opt/rabbitmq/plugins/prometheus_rabbitmq_exporter-3.7.2.3.ez
