{
 "title": "docker hosts",
 "description": "docker monitor",
 "tags": [
  "prometheus",
  "node_exporter"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(node_load1{job=\"node_exporter\"}, env)"
   },
   {
    "name": "app",
    "label": "App",
    "query": "label_values(node_load1{job=\"node_exporter\",env=~\"$environment\"}, app)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_load1{job=\"node_exporter\",env=~\"$environment\",app=~\"$app\"}, instance)"
   },
   {
    "name": "filesystem_mountpoint",
    "query": "query_result(node_filesystem_size{job=\"node_exporter\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint!~\".*docker.*\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(job, instance)(node_load1{job=\"node_exporter\", instance=~\"$node:.*\"}) / count by(job, instance)(count by(job, instance, cpu)(node_cpu{job=\"node_exporter\", instance=~\"$node:.*\"}))"
    }
   ]
  },
  {
   "title": "State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"node_exporter\", instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by(cpu)(node_cpu{job=\"node_exporter\", instance=~\"$node:.*\"}))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_MemTotal{job=\"node_exporter\", instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "All disks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_size{job=\"node_exporter\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint!=\"/var/lib/docker/aufs\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - node_boot_time{job=\"node_exporter\", instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(mode)(irate(node_cpu{job=\"node_exporter\", instance=~\"$node:.*\", mode!=\"idle\"}[5m])) > 0",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_load1{job=\"node_exporter\", instance=~\"$node:.*\"}[5m])",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "irate(node_load5{job=\"node_exporter\", instance=~\"$node:.*\"}[5m])",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "irate(node_load15{job=\"node_exporter\", instance=~\"$node:.*\"}[5m])",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Buffers{job=\"node_exporter\", instance=~\"$node:.*\"}",
     "legendFormat": "buffers"
    },
    {
     "expr": "node_memory_Cached{job=\"node_exporter\", instance=~\"$node:.*\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_MemFree{job=\"node_exporter\", instance=~\"$node:.*\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_MemTotal{job=\"node_exporter\", instance=~\"$node:.*\"} - node_memory_MemFree{job=\"node_exporter\", instance=~\"$node:.*\"} - node_memory_Cached{job=\"node_exporter\", instance=~\"$node:.*\"} - node_memory_Buffers{job=\"node_exporter\", instance=~\"$node:.*\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes{job=\"node_exporter\", instance=~\"$node:.*\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*|cali.*|docker.*|tunl.*\"}[5m]) > 0",
     "legendFormat": "{{device}} outbound"
    },
    {
     "expr": "irate(node_network_receive_bytes{job=\"node_exporter\", instance=~\"$node:.*\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*|cali.*|docker.*|tunl.*\"}[5m]) > 0",
     "legendFormat": "{{device}} inbound"
    }
   ]
  },
  {
   "title": "Disk I/O utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_ms{job=\"node_exporter\", instance=~\"$node:.*\", device!~\"sr.*\"}[5m]) / 1000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(node_context_switches{job=\"node_exporter\", instance=~\"$node:.*\"}[$interval]) or irate(node_context_switches{job=\"node_exporter\", instance=~\"$node:.*\"}[5m])",
     "legendFormat": "Context Switches"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(node_intr{job=\"node_exporter\", instance=~\"$node:.*\"}[$interval]) or irate(node_intr{job=\"node_exporter\", instance=~\"$node:.*\"}[5m])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "I/O Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pgpgin{job=\"node_exporter\", instance=~\"$node:.*\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{job=\"node_exporter\", instance=~\"$node:.*\"}[5m]) * 1024",
     "legendFormat": "Page In"
    },
    {
     "expr": "rate(node_vmstat_pgpgout{job=\"node_exporter\", instance=~\"$node:.*\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{job=\"node_exporter\", instance=~\"$node:.*\"}[5m]) * 1024",
     "legendFormat": "Page Out"
    }
   ]
  },
  {
   "title": "Filesystem $filesystem_mountpoint usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "repeat": "filesystem_mountpoint",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size{job=\"node_exporter\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint=\"$filesystem_mountpoint\"} - node_filesystem_free{job=\"node_exporter\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint=\"$filesystem_mountpoint\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_filesystem_free{job=\"node_exporter\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint=\"$filesystem_mountpoint\"}",
     "legendFormat": "free"
    }
   ]
  }
 ]
}