# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define :etcd0 do |etcd0|
    etcd0.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", "etcd0", "--memory", "512"]
    end
    etcd0.vm.box = "base"
    etcd0.vm.hostname = "etcd0"
    etcd0.vm.network :private_network, ip: "11.11.1.1"
  end

  config.vm.define :etcd1 do |etcd1|
    etcd1.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", "etcd1", "--memory", "512"]
    end
    etcd1.vm.box = "base"
    etcd1.vm.hostname = "etcd1"
    etcd1.vm.network :private_network, ip: "11.11.1.2"
  end

  config.vm.define :etcd2 do |etcd2|
    etcd2.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", "etcd2", "--memory", "512"]
    end
    etcd2.vm.box = "base"
    etcd2.vm.hostname = "etcd2"
    etcd2.vm.network :private_network, ip: "11.11.1.3"
  end
end
